### ISSUE TITLE
Need some timezone support.

### ISSUE THREAD

**Issue by robmarkoski** [alexellis/phototimer#2]
After banging my head for a while, I realised the Docker images timezone was not synced to my local one.

Fixed it with adding the following to Dockerfile

```
ENV TZ=Australia/Perth
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

I didn't add a pull request, as I thought you would rather add functionality in the python script and allow timezones to be set in config.py

**Comment by alexellis** [comment]
@robmarkoski thanks for raising this issue and for using Phototimer. I came across the same issue when in Austin, Texas which has a different time zone to default (UTC).

In practice I found that changing the `TZ` variable via Docker is enough to get the correct time.

```
docker run ... -e TZ=Europe/London ...
```

The supporting blog post had an update for this too. http://blog.alexellis.io/tag/picamera/
